name: ridebot_pro

description: Advanced Ride Automation Assistant

publish_to: "none"


version: 1.0.0+1


environment:
  sdk: ">=3.4.0 <4.0.0"



dependencies:


  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8


  # State Management
  provider: ^6.1.2


  # Local Database
  sqflite: ^2.3.3+1


  # Storage
  shared_preferences: ^2.3.2


  # Notifications
  flutter_local_notifications: ^17.2.3


  # Permissions
  permission_handler: ^11.3.1


  # Location
  geolocator: ^13.0.1


  # Android Settings
  android_intent_plus: ^5.2.0



dev_dependencies:


  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true
